spring:
  application:
    name: ProductService
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: HKhk61+-
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}